name: Ant Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: actions/cache@v4
      id: cache-netbeans
      with:
        path: ./netbeans/
        key: ${{ runner.os }}-netbeans-${{ hashFiles('**/netbeans/nb/build_info') }}
        restore-keys: |
          ${{ runner.os }}-netbeans-
          
      # TODO: Create an Action
    - name: Download NetBeans 18
      run: wget -q https://archive.apache.org/dist/netbeans/netbeans/18/netbeans-18-bin.zip
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
      
    - name: Download NetBeans 18 archive checksum
      run: wget -q https://archive.apache.org/dist/netbeans/netbeans/18/netbeans-18-bin.zip.sha512
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
      
    - name: Verify NetBeans 18 archive
      run: sha512sum -c netbeans-18-bin.zip.sha512
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
    
    - name: Unzip Netbeans 18 Archive
      run: unzip -q netbeans-18-bin.zip
      if: steps.cache-netbeans.outputs.cache-hit != 'true'

    - name: Build NBMs with Ant
      run: >-
        ant -noinput -buildfile build.xml
        -Dnbplatform.default.netbeans.dest.dir=${{ github.workspace }}/netbeans
        -Dnbplatform.default.harness.dir=${{ github.workspace }}/netbeans/harness
        nbms
      
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: build/updates/
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
